#define NPROC        64  // 最大进程数
#define NCPU          8  // 最大CPU数
#define NOFILE       16  // 每个进程打开的最大文件数
#define NFILE       100  // 系统范围内打开的最大文件数
#define NINODE       50  // 最大活动i节点数
#define NDEV         10  // 最大主设备号
#define ROOTDEV       1  // 文件系统根磁盘的设备号
#define MAXARG       32  // exec参数的最大数量
#define MAXOPBLOCKS  10  // 任何文件系统操作写入的最大块数
#define LOGBLOCKS    (MAXOPBLOCKS*3)  // 磁盘日志中的最大数据块数
#define NBUF         (MAXOPBLOCKS*3)  // 磁盘块缓存的大小
#define FSSIZE       2000  // 文件系统的块大小
#define MAXPATH      128   // 最大文件路径名长度
#define USERSTACK    1     // 用户栈页数