// 系统调用 定义
#define SYS_fork     1  // 创建一个新进程
#define SYS_exit     2  // 退出当前进程
#define SYS_wait     3  // 等待一个子进程退出
#define SYS_pipe     4  // 创建一个管道
#define SYS_read     5  // 从文件读取数据
#define SYS_kill     6  // 终止一个进程
#define SYS_exec     7  // 执行一个程序
#define SYS_fstat    8  // 获取文件状态
#define SYS_chdir    9  // 改变当前工作目录
#define SYS_dup     10  // 复制一个文件描述符
#define SYS_getpid  11  // 获取当前进程ID
#define SYS_sbrk    12  // 增加进程内存
#define SYS_sleep   13  // 使进程休眠
#define SYS_uptime  14  // 获取系统运行时间
#define SYS_open    15  // 打开一个文件
#define SYS_write   16  // 向文件写入数据
#define SYS_mknod   17  // 创建一个设备文件
#define SYS_unlink  18  // 删除一个文件
#define SYS_link    19  // 创建一个文件的硬链接
#define SYS_mkdir   20  // 创建一个目录
#define SYS_close   21  // 关闭一个文件
